          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):https://github.com/bshwang/rteach-addon/blob/main/resources/error_msg.txt
  File "C:\Users\bsoo.hwang.SECDS\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\rteach\ops\ops_teach_main.py", line 174, in execute
    q_sel = min(sols, key=_score)
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bsoo.hwang.SECDS\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\rteach\ops\ops_teach_main.py", line 171, in _score
    return sum(abs(stable_ang_diff(q[j], master_q[j]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bsoo.hwang.SECDS\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\rteach\ops\ops_teach_main.py", line 171, in <genexpr>
    return sum(abs(stable_ang_diff(q[j], master_q[j]))
                                   ~^^^
IndexError: index 6 is out of bounds for axis 0 with size 6
Location: D:\Blender Foundation\Blender 4.3\4.3\scripts\modules\bpy\ops.py:107
